### ISSUE TITLE
microshift_image_pubkey_file doesn't work as file path

### ISSUE THREAD

**Issue by maxamillion** [ansible-collections/edge.microshift#8]
##### SUMMARY
Currently the `microshift_image_pubkey_file` variable looks as though it wants a filename, but in the role it doesn't ever pull the pubkey out of the file and inject it into the import for the `infra.osbuild.builder` role.

I had to do the following in my playbook to make this work:

```yaml
- name: Build RHEL for Edge + Microshift
  hosts: rhel8builder
  gather_facts: true
  vars:
    pubkey_file: "~/.ssh/id_rsa.pub"
  tasks:
    - name: slurp pubkey file
      ansible.builtin.slurp:
        src: "{{ pubkey_file }}"
      register: slurp_out
      delegate_to: localhost

    - name: Create image with microshift
      ansible.builtin.import_role:
        name: edge.microshift.image_builder
      vars:
        microshift_image_compose_customizations:
          user:
            name: "edge"
            description: "test user"
            password: "openshift"
            key: "{{ slurp_out['content'] | b64decode | trim }}"
            groups: '["users", "wheel"]'
          services:
            enabled:
              - sshd
```

##### ISSUE TYPE
- Bug Report
